[package]
description = "Dremio Rust client"
edition = "2021"
license = "MIT"
name = "dremio-rs"
version = "0.2.0"
repository = "https://github.com/vrd83/dremio-rs"

[dependencies]
arrow = "56.1.0"
arrow-flight = { version = "55.1.0", features = ["flight-sql-experimental"] }
futures = "0.3.31"
parquet = "55.1.0"
thiserror = "2.0.12"
tonic = "0.12.3"

[dev-dependencies]
testcontainers = "0.24.0"
tokio = { version = "1.45.1", features = ["full"] }
reqwest = "0.12.12"
